/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/AdminUserRolesView': RouteRecordInfo<'/admin/AdminUserRolesView', '/admin/AdminUserRolesView', Record<never, never>, Record<never, never>>,
    '/admin/components/DashboardHeader': RouteRecordInfo<'/admin/components/DashboardHeader', '/admin/components/DashboardHeader', Record<never, never>, Record<never, never>>,
    '/admin/components/DashboardStats': RouteRecordInfo<'/admin/components/DashboardStats', '/admin/components/DashboardStats', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/DeleteUserDialog': RouteRecordInfo<'/admin/components/dialogs/DeleteUserDialog', '/admin/components/dialogs/DeleteUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/EditUserDialog': RouteRecordInfo<'/admin/components/dialogs/EditUserDialog', '/admin/components/dialogs/EditUserDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/dialogs/UserDetailsDialog': RouteRecordInfo<'/admin/components/dialogs/UserDetailsDialog', '/admin/components/dialogs/UserDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackCard': RouteRecordInfo<'/admin/components/FeedbackCard', '/admin/components/FeedbackCard', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackFilters': RouteRecordInfo<'/admin/components/FeedbackFilters', '/admin/components/FeedbackFilters', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackList': RouteRecordInfo<'/admin/components/FeedbackList', '/admin/components/FeedbackList', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackSection': RouteRecordInfo<'/admin/components/FeedbackSection', '/admin/components/FeedbackSection', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackStats': RouteRecordInfo<'/admin/components/FeedbackStats', '/admin/components/FeedbackStats', Record<never, never>, Record<never, never>>,
    '/admin/components/FeedbackTabs': RouteRecordInfo<'/admin/components/FeedbackTabs', '/admin/components/FeedbackTabs', Record<never, never>, Record<never, never>>,
    '/admin/components/QuickActionsCard': RouteRecordInfo<'/admin/components/QuickActionsCard', '/admin/components/QuickActionsCard', Record<never, never>, Record<never, never>>,
    '/admin/components/RecentActivitiesCard': RouteRecordInfo<'/admin/components/RecentActivitiesCard', '/admin/components/RecentActivitiesCard', Record<never, never>, Record<never, never>>,
    '/admin/components/SystemStatusCard': RouteRecordInfo<'/admin/components/SystemStatusCard', '/admin/components/SystemStatusCard', Record<never, never>, Record<never, never>>,
    '/admin/components/UserManagementTable': RouteRecordInfo<'/admin/components/UserManagementTable', '/admin/components/UserManagementTable', Record<never, never>, Record<never, never>>,
    '/admin/DashboardView': RouteRecordInfo<'/admin/DashboardView', '/admin/DashboardView', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/AdminUserRolesDialog': RouteRecordInfo<'/admin/dialogs/AdminUserRolesDialog', '/admin/dialogs/AdminUserRolesDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/DeleteConfirmDialog': RouteRecordInfo<'/admin/dialogs/DeleteConfirmDialog', '/admin/dialogs/DeleteConfirmDialog', Record<never, never>, Record<never, never>>,
    '/admin/dialogs/FeedbackDetailsDialog': RouteRecordInfo<'/admin/dialogs/FeedbackDetailsDialog', '/admin/dialogs/FeedbackDetailsDialog', Record<never, never>, Record<never, never>>,
    '/admin/FeedbackManagementView': RouteRecordInfo<'/admin/FeedbackManagementView', '/admin/FeedbackManagementView', Record<never, never>, Record<never, never>>,
    '/admin/UserManagementView': RouteRecordInfo<'/admin/UserManagementView', '/admin/UserManagementView', Record<never, never>, Record<never, never>>,
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/barangay/components/AnnouncementsTab': RouteRecordInfo<'/barangay/components/AnnouncementsTab', '/barangay/components/AnnouncementsTab', Record<never, never>, Record<never, never>>,
    '/barangay/components/collectorDialog': RouteRecordInfo<'/barangay/components/collectorDialog', '/barangay/components/collectorDialog', Record<never, never>, Record<never, never>>,
    '/barangay/components/EWasteMonitoring': RouteRecordInfo<'/barangay/components/EWasteMonitoring', '/barangay/components/EWasteMonitoring', Record<never, never>, Record<never, never>>,
    '/barangay/components/FeedbackAnnouncementTabs': RouteRecordInfo<'/barangay/components/FeedbackAnnouncementTabs', '/barangay/components/FeedbackAnnouncementTabs', Record<never, never>, Record<never, never>>,
    '/barangay/components/FeedbackTab': RouteRecordInfo<'/barangay/components/FeedbackTab', '/barangay/components/FeedbackTab', Record<never, never>, Record<never, never>>,
    '/barangay/components/requestsTable': RouteRecordInfo<'/barangay/components/requestsTable', '/barangay/components/requestsTable', Record<never, never>, Record<never, never>>,
    '/barangay/components/statCards': RouteRecordInfo<'/barangay/components/statCards', '/barangay/components/statCards', Record<never, never>, Record<never, never>>,
    '/barangay/MonitoringView': RouteRecordInfo<'/barangay/MonitoringView', '/barangay/MonitoringView', Record<never, never>, Record<never, never>>,
    '/barangay/PickupsView': RouteRecordInfo<'/barangay/PickupsView', '/barangay/PickupsView', Record<never, never>, Record<never, never>>,
    '/barangay/ReportAnalysisView': RouteRecordInfo<'/barangay/ReportAnalysisView', '/barangay/ReportAnalysisView', Record<never, never>, Record<never, never>>,
    '/collectors/components/RequestsHistoryWidget': RouteRecordInfo<'/collectors/components/RequestsHistoryWidget', '/collectors/components/RequestsHistoryWidget', Record<never, never>, Record<never, never>>,
    '/collectors/components/RequestsPagination': RouteRecordInfo<'/collectors/components/RequestsPagination', '/collectors/components/RequestsPagination', Record<never, never>, Record<never, never>>,
    '/collectors/components/RequestsWidget': RouteRecordInfo<'/collectors/components/RequestsWidget', '/collectors/components/RequestsWidget', Record<never, never>, Record<never, never>>,
    '/collectors/dialogs/RequestDialog': RouteRecordInfo<'/collectors/dialogs/RequestDialog', '/collectors/dialogs/RequestDialog', Record<never, never>, Record<never, never>>,
    '/collectors/RequestsHistoryView': RouteRecordInfo<'/collectors/RequestsHistoryView', '/collectors/RequestsHistoryView', Record<never, never>, Record<never, never>>,
    '/collectors/RequestsView': RouteRecordInfo<'/collectors/RequestsView', '/collectors/RequestsView', Record<never, never>, Record<never, never>>,
    '/ForbiddenView': RouteRecordInfo<'/ForbiddenView', '/ForbiddenView', Record<never, never>, Record<never, never>>,
    '/HomeView': RouteRecordInfo<'/HomeView', '/HomeView', Record<never, never>, Record<never, never>>,
    '/NotFound': RouteRecordInfo<'/NotFound', '/NotFound', Record<never, never>, Record<never, never>>,
    '/residents/AnnouncementsWidget': RouteRecordInfo<'/residents/AnnouncementsWidget', '/residents/AnnouncementsWidget', Record<never, never>, Record<never, never>>,
    '/residents/CollectionRequestWidget': RouteRecordInfo<'/residents/CollectionRequestWidget', '/residents/CollectionRequestWidget', Record<never, never>, Record<never, never>>,
    '/residents/CollectionSender': RouteRecordInfo<'/residents/CollectionSender', '/residents/CollectionSender', Record<never, never>, Record<never, never>>,
    '/residents/DailyAnnouncement': RouteRecordInfo<'/residents/DailyAnnouncement', '/residents/DailyAnnouncement', Record<never, never>, Record<never, never>>,
    '/residents/dialogs/AnnouncementDetailDialog': RouteRecordInfo<'/residents/dialogs/AnnouncementDetailDialog', '/residents/dialogs/AnnouncementDetailDialog', Record<never, never>, Record<never, never>>,
    '/residents/dialogs/CollectionSenderDialog': RouteRecordInfo<'/residents/dialogs/CollectionSenderDialog', '/residents/dialogs/CollectionSenderDialog', Record<never, never>, Record<never, never>>,
    '/residents/dialogs/CreateFeedbackDialog': RouteRecordInfo<'/residents/dialogs/CreateFeedbackDialog', '/residents/dialogs/CreateFeedbackDialog', Record<never, never>, Record<never, never>>,
    '/residents/dialogs/MyCollectionsDialog': RouteRecordInfo<'/residents/dialogs/MyCollectionsDialog', '/residents/dialogs/MyCollectionsDialog', Record<never, never>, Record<never, never>>,
    '/residents/MyCollectionsView': RouteRecordInfo<'/residents/MyCollectionsView', '/residents/MyCollectionsView', Record<never, never>, Record<never, never>>,
    '/residents/MyCollectionsWidget': RouteRecordInfo<'/residents/MyCollectionsWidget', '/residents/MyCollectionsWidget', Record<never, never>, Record<never, never>>,
    '/residents/MyFeedbackView': RouteRecordInfo<'/residents/MyFeedbackView', '/residents/MyFeedbackView', Record<never, never>, Record<never, never>>,
  }
}
