create table if not exists "public"."purok_monitoring" (
    "id" bigint generated by default as identity not null primary key,
    "name" text not null unique,
    "status" text not null default 'pending',
    "last_surveyed" timestamp with time zone,
    "collection_id" bigint references "public"."collections" ("id"),
    "notes" text,
    "created_at" timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed data
insert into "public"."purok_monitoring" ("name") values
('Purok 1'),
('Purok 2'),
('Purok 3'),
('Purok 4'),
('Purok 5'),
('Purok 6'),
('Purok 7'),
('Purok 8'),
('Purok 9')
on conflict ("name") do nothing;
